apiVersion: v1
kind: Service
metadata:
  name: {{ default "api" .Values.api.name }}
  labels:
    app: {{ default "api" .Values.api.name }}
spec:
  selector:
    app: {{ default "api" .Values.api.name }} # Label do Deployment
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.containerPort }}
