apiVersion: v1
kind: Service
metadata:
  name: {{ default "worker" .Values.worker.name }}
  labels:
    app: {{ default "worker" .Values.worker.name }}
spec:
  selector:
    app: {{ default "worker" .Values.worker.name }} # Label do Deployment
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.worker.containerPort }}
