apiVersion: v1
kind: Service
metadata:
  name: {{ default "worker-user" .Values.workerUser.name }}
  labels:
    app: {{ default "worker-user" .Values.workerUser.name }}
spec:
  selector:
    app: {{ default "worker-user" .Values.workerUser.name }} # Label do Deployment
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.workerUser.containerPort }}
