global:
  environment: staging
 
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 1
    serviceAccountRole: "arn:aws:iam::017820684017:role/reservas"

  minReadySeconds: 120

  image:
    repository: 017820684017.dkr.ecr.us-west-2.amazonaws.com/seazone-reservas-api
    tag: "0.33.1-rc.1"
    pullPolicy: IfNotPresent

  nodeAffinityName: "apps"

api:
  name: api-seazone-reservas

  requests:
    cpu: 500m
    memory: 1G
   
  limits:
    cpu: 700m
    memory: 2G
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 1
    maxReplicas: 2

  IngressRoute:
    enable: true
    serviceName: "api-seazone-reservas"
    host: "api-staging."

workerUser:
  name: worker-user-seazone-reservas

  requests:
    cpu: 500m
    memory: 1G
   
  limits:
    cpu: 700m
    memory: 2G
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 1
    maxReplicas: 2

worker:
  name: worker-seazone-reservas

  requests:
    cpu: 500m
    memory: 1G
   
  limits:
    cpu: 700m
    memory: 2G
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 2
    maxReplicas: 3

scheduler:
  name: scheduler-seazone-reservas

  requests:
    cpu: 200m
    memory: 200Mi

  limits:
    cpu: 400m
    memory: 400Mi
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 1
    maxReplicas: 1
