global:
  environment: production
 
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
    serviceAccountRole: "arn:aws:iam::711387131913:role/reservas"

  minReadySeconds: 120

  image:
    repository: 711387131913.dkr.ecr.us-west-2.amazonaws.com/seazone-reservas-api
    tag: "0.38.14"
    pullPolicy: IfNotPresent

  nodeAffinityName: "apps"

api:
  name: api-seazone-reservas

  requests:
    cpu: 400m
    memory: 600Mi
   
  limits:
    cpu: 600m
    memory: 800Mi
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 4
    maxReplicas: 8

  IngressRoute:
    enable: true
    serviceName: "api-seazone-reservas"
    host: "api."

workerUser:
  name: worker-user-seazone-reservas

  requests:
    cpu: 450m
    memory: 200Mi
   
  limits:
    cpu: 650m
    memory: 400Mi
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 3
    maxReplicas: 6

worker:
  name: worker-seazone-reservas

  requests:
    cpu: 800m
    memory: 1G
   
  limits:
    cpu: 1200m
    memory: 2G
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 3
    maxReplicas: 15

scheduler:
  name: scheduler-seazone-reservas

  requests:
    cpu: 50m
    memory: 150Mi

  limits:
    cpu: 150m
    memory: 250Mi
  containerPort: 8001
  healthcheckPath: /health
  hpa:
    minReplicas: 1
    maxReplicas: 1
