name: Deploy Production
on:
  push:
    paths:
      - "helm/values.yaml"
jobs:
  deploy-tag-prd:
    name: Deploy New Image Tag Prod
    permissions:
      contents: read
      id-token: write  
    uses: seazone-tech/governanca-workflows-template/.github/workflows/app-deploy-helm.yaml@main
    with:
      environment: 'production'
      app_name: 'reservas'
      action: 'deploy'
    secrets:
      account_region: ${{ secrets.AWS_PRODUCTION_ACCOUNT_REGION }}
      account_id: ${{ secrets.AWS_PRODUCTION_ACCOUNT_ID }}
      deployment_role: ${{ secrets.AWS_PRODUCTION_DEPLOYMENT_ROLE }}