name: Deploy Staging
on:
  push:
    paths:
      - "helm/values-staging.yaml"
jobs:
  deploy-tag-stg:
    name: Deploy New Image Tag Stage
    permissions:
      contents: read
      id-token: write  
    uses: seazone-tech/governanca-workflows-template/.github/workflows/app-deploy-helm.yaml@main
    with:
      environment: 'staging'
      app_name: 'reservas'
      action: 'deploy'
    secrets:
      account_region: ${{ secrets.AWS_STAGING_ACCOUNT_REGION }}
      account_id: ${{ secrets.AWS_STAGING_ACCOUNT_ID }}
      deployment_role: ${{ secrets.AWS_STAGING_DEPLOYMENT_ROLE }}