name: Scale Staging Scheduler
on:
  workflow_dispatch:
    inputs:
      replicas:
        description: 'Número de réplicas (ex: 2 para ambiente normal ou 6 para alta disponibilidade)'
        required: true
        default: '2'
jobs:
  scale-app:
    name: Scale Application Deployment
    permissions:
      contents: read
      id-token: write
    uses: seazone-tech/governanca-workflows-template/.github/workflows/app-eks-management.yaml@main
    with:
      environment: 'staging'
      app_name: 'reservas'
      action: 'scale'
      replicas: ${{ github.event.inputs.replicas }}
      hpa_path: 'scheduler.hpa.minReplicas'
      deploy_name: 'scheduler-seazone-reservas'
    secrets:
      account_region: ${{ secrets.AWS_STAGING_ACCOUNT_REGION }}
      account_id: ${{ secrets.AWS_STAGING_ACCOUNT_ID }}
      deployment_role: ${{ secrets.AWS_STAGING_DEPLOYMENT_ROLE }}
