name: Scale Staging Worker User
on:
  workflow_dispatch:
    inputs:
      disponibilidade:
        description: 'Tipo de disponibilidade'
        required: true
        default: 'normal'
        type: choice
        options:
        - normal
        - alta
  schedule:
  # Segunda a sexta às 7h
  - cron: '0 10 * * 1-5'
jobs:
  scale-app:
    name: Scale Application Deployment
    permissions:
      contents: read
      id-token: write
    uses: seazone-tech/governanca-workflows-template/.github/workflows/app-eks-management.yaml@main
    with:
      environment: 'staging'
      app_name: 'reservas'
      action: 'scale'
      replicas: ${{ github.event.inputs.disponibilidade == 'alta' && github.event.inputs.WORKER_USER_HIGH_AVAILABILITY || github.event_name == 'schedule' && '2' || '2' }}
      hpa_path: 'workerUser.hpa.minReplicas'
      deploy_name: 'worker-user-seazone-reservas'
    secrets:
      account_region: ${{ secrets.AWS_STAGING_ACCOUNT_REGION }}
      account_id: ${{ secrets.AWS_STAGING_ACCOUNT_ID }}
      deployment_role: ${{ secrets.AWS_STAGING_DEPLOYMENT_ROLE }}
